# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_key_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartycredentials',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
